//Draw score
//This is a huuuge mess because I wanted it to space the numbers the same distance apart even if the digits were different widths (eg 1 and 7)
draw_sprite(spr_scorebg,0,view_xview,view_yview)
draw_set_font(fnt_score)
global.stringgamescore = string(global.gamescore)
draw_set_halign(fa_center)
draw_set_valign(fa_center)
if(global.gamescore < 10){
    scoredigit1 = string_char_at(global.stringgamescore,1)
    draw_text_transformed_color(view_xview+13,view_yview+20,0,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+13,view_yview+20,0,c_white,c_white,c_ltgray,c_ltgray,1)
    draw_text_transformed_color(view_xview+36,view_yview+20,0,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+36,view_yview+20,0,c_white,c_white,c_ltgray,c_ltgray,1)
    draw_text_transformed_color(view_xview+60,view_yview+20,0,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+60,view_yview+20,0,c_white,c_white,c_ltgray,c_ltgray,1)
    draw_text_transformed_color(view_xview+83,view_yview+20,0,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+83,view_yview+20,0,c_white,c_white,c_ltgray,c_ltgray,1)
    draw_text_transformed_color(view_xview+107,view_yview+20,scoredigit1,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+107,view_yview+20,scoredigit1,c_white,c_white,c_ltgray,c_ltgray,1)
}
if(global.gamescore >= 10 and global.gamescore < 100){
    scoredigit1 = string_char_at(global.stringgamescore,2)
    scoredigit2 = string_char_at(global.stringgamescore,1)
    draw_text_transformed_color(view_xview+13,view_yview+20,0,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+13,view_yview+20,0,c_white,c_white,c_ltgray,c_ltgray,1)
    draw_text_transformed_color(view_xview+36,view_yview+20,0,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+36,view_yview+20,0,c_white,c_white,c_ltgray,c_ltgray,1)
    draw_text_transformed_color(view_xview+60,view_yview+20,0,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+60,view_yview+20,0,c_white,c_white,c_ltgray,c_ltgray,1)
    draw_text_transformed_color(view_xview+83,view_yview+20,scoredigit2,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+83,view_yview+20,scoredigit2,c_white,c_white,c_ltgray,c_ltgray,1)
    draw_text_transformed_color(view_xview+107,view_yview+20,scoredigit1,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+107,view_yview+20,scoredigit1,c_white,c_white,c_ltgray,c_ltgray,1)
}
if(global.gamescore >= 100 and global.gamescore < 1000){
    scoredigit1 = string_char_at(global.stringgamescore,3)
    scoredigit2 = string_char_at(global.stringgamescore,2)
    scoredigit3 = string_char_at(global.stringgamescore,1)
    draw_text_transformed_color(view_xview+13,view_yview+20,0,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+13,view_yview+20,0,c_white,c_white,c_ltgray,c_ltgray,1)
    draw_text_transformed_color(view_xview+36,view_yview+20,0,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+36,view_yview+20,0,c_white,c_white,c_ltgray,c_ltgray,1)
    draw_text_transformed_color(view_xview+60,view_yview+20,scoredigit3,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+60,view_yview+20,scoredigit3,c_white,c_white,c_ltgray,c_ltgray,1)
    draw_text_transformed_color(view_xview+83,view_yview+20,scoredigit2,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+83,view_yview+20,scoredigit2,c_white,c_white,c_ltgray,c_ltgray,1)
    draw_text_transformed_color(view_xview+107,view_yview+20,scoredigit1,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+107,view_yview+20,scoredigit1,c_white,c_white,c_ltgray,c_ltgray,1)
}
if(global.gamescore >= 1000 and global.gamescore < 10000){
    scoredigit1 = string_char_at(global.stringgamescore,4)
    scoredigit2 = string_char_at(global.stringgamescore,3)
    scoredigit3 = string_char_at(global.stringgamescore,2)
    scoredigit4 = string_char_at(global.stringgamescore,1)
    draw_text_transformed_color(view_xview+13,view_yview+20,0,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+13,view_yview+20,0,c_white,c_white,c_ltgray,c_ltgray,1)
    draw_text_transformed_color(view_xview+36,view_yview+20,scoredigit4,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+36,view_yview+20,scoredigit4,c_white,c_white,c_ltgray,c_ltgray,1)
    draw_text_transformed_color(view_xview+60,view_yview+20,scoredigit3,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+60,view_yview+20,scoredigit3,c_white,c_white,c_ltgray,c_ltgray,1)
    draw_text_transformed_color(view_xview+83,view_yview+20,scoredigit2,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+83,view_yview+20,scoredigit2,c_white,c_white,c_ltgray,c_ltgray,1)
    draw_text_transformed_color(view_xview+107,view_yview+20,scoredigit1,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+107,view_yview+20,scoredigit1,c_white,c_white,c_ltgray,c_ltgray,1)
}
if(global.gamescore >= 10000 and global.gamescore < 100000){
    scoredigit1 = string_char_at(global.stringgamescore,5)
    scoredigit2 = string_char_at(global.stringgamescore,4)
    scoredigit3 = string_char_at(global.stringgamescore,3)
    scoredigit4 = string_char_at(global.stringgamescore,2)
    scoredigit5 = string_char_at(global.stringgamescore,1)
    draw_text_transformed_color(view_xview+13,view_yview+20,scoredigit5,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+13,view_yview+20,scoredigit5,c_white,c_white,c_ltgray,c_ltgray,1)
    draw_text_transformed_color(view_xview+36,view_yview+20,scoredigit4,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+36,view_yview+20,scoredigit4,c_white,c_white,c_ltgray,c_ltgray,1)
    draw_text_transformed_color(view_xview+60,view_yview+20,scoredigit3,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+60,view_yview+20,scoredigit3,c_white,c_white,c_ltgray,c_ltgray,1)
    draw_text_transformed_color(view_xview+83,view_yview+20,scoredigit2,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+83,view_yview+20,scoredigit2,c_white,c_white,c_ltgray,c_ltgray,1)
    draw_text_transformed_color(view_xview+107,view_yview+20,scoredigit1,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+107,view_yview+20,scoredigit1,c_white,c_white,c_ltgray,c_ltgray,1)
}
if(global.gamescore >= 100000){
    draw_text_transformed_color(view_xview+13,view_yview+20,9,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+13,view_yview+20,9,c_white,c_white,c_ltgray,c_ltgray,1)
    draw_text_transformed_color(view_xview+36,view_yview+20,9,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+36,view_yview+20,9,c_white,c_white,c_ltgray,c_ltgray,1)
    draw_text_transformed_color(view_xview+60,view_yview+20,9,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+60,view_yview+20,9,c_white,c_white,c_ltgray,c_ltgray,1)
    draw_text_transformed_color(view_xview+83,view_yview+20,9,1.15,1.15,0,c_gray,c_gray,c_dkgray,c_dkgray,1)
    draw_text_color(view_xview+83,view_yview+20,9,c_white,c_white,c_ltgray,c_ltgray,1)
}
draw_set_halign(fa_left)
draw_set_valign(fa_top)
