skel_pelvis[0] = smooth(skel_pelvis[0],skel_pelvis_g[0],20)
skel_pelvis[1] = smooth(skel_pelvis[1],skel_pelvis_g[1],20)
skel_torso[0] = skel_pelvis[0]
skel_torso[1] = skel_pelvis[1] - 50
skel_rshoulder[0] = skel_torso[0] - 10
skel_rshoulder[1] = skel_torso[1]
skel_lshoulder[0] = skel_torso[0] + 10
skel_lshoulder[1] = skel_torso[1]
skel_relbow[0] = skel_rshoulder[0] - 20
skel_relbow[1] = skel_rshoulder[1]
skel_lelbow[0] = skel_lshoulder[0] + 20
skel_lelbow[1] = skel_lshoulder[1]
skel_rhand[0] = skel_relbow[0] - 20
skel_rhand[1] = skel_relbow[1]
skel_lhand[0] = skel_lelbow[0] + 20
skel_lhand[1] = skel_lelbow[1]
